SUPABASE_URL = "https://vqukmlutaqthsmaprieb.supabase.co/"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxdWttbHV0YXF0aHNtYXByaWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzIwMzAsImV4cCI6MjA2MDQ0ODAzMH0.hwwcVLCYDYLVHfajYD77EHT0H2_0GmTv3kAOTLtlpbo"
GEMINI_API_KEY = "AIzaSyCyJqta7qTx6m6_mvIR3qRNyr67XSWNJ-4"

